# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "C:/Users/Administrator/AppData/Local/Programs/Python/Python312/Lib/site-packages/PyQt5/Qt5/plugins/platforms"
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(755, 528)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(230, 10, 281, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 71, 16))
        self.label_2.setObjectName("label_2")
        self.btn_verify = QtWidgets.QPushButton(Dialog)
        self.btn_verify.setGeometry(QtCore.QRect(420, 470, 93, 28))
        self.btn_verify.setObjectName("btn_verify")
        self.txt_sign = QtWidgets.QTextEdit(Dialog)
        self.txt_sign.setGeometry(QtCore.QRect(140, 320, 571, 87))
        self.txt_sign.setObjectName("txt_sign")
        self.txt_info = QtWidgets.QTextEdit(Dialog)
        self.txt_info.setGeometry(QtCore.QRect(140, 120, 571, 87))
        self.txt_info.setObjectName("txt_info")
        self.btn_gen_keys = QtWidgets.QPushButton(Dialog)
        self.btn_gen_keys.setGeometry(QtCore.QRect(520, 40, 141, 28))
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        self.btn_sign = QtWidgets.QPushButton(Dialog)
        self.btn_sign.setGeometry(QtCore.QRect(260, 470, 93, 28))
        self.btn_sign.setObjectName("btn_sign")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 320, 71, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "ECC CIPHER"))
        self.label_2.setText(_translate("Dialog", "Infomation"))
        self.btn_verify.setText(_translate("Dialog", "varyfi"))
        self.btn_gen_keys.setText(_translate("Dialog", "Gennerate keys"))
        self.btn_sign.setText(_translate("Dialog", "Sign"))
        self.label_3.setText(_translate("Dialog", "Signature"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
